version: "3"
services:
  react-app-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: demo_f:latest
    ports:
     - "3000:3000"
    volumes:
     - ./src:/app/src
    environment:
     - CHOKIDAR_USEPOLLING=true
     - WATCHPACK_POLLING=true