apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactfrontend-deployment
  labels:
    app: reactfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactfrontend
  template:
    metadata:
      labels:
        app: reactfrontend
    spec:
      containers:
      - name: reactfrontend-container
        image: scott2srikanth/myfsdcc_frontend:latest
        ports:
        - containerPort: 3001
        
---

apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer
  selector:
    app: reactfrontend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
